### ISSUE TITLE
Fingerprint do not work in some 3rd party apps

### ISSUE THREAD

**Issue by fcuzzocrea** [8890q/android_device_samsung_universal8890-common#1]
Same issue which is present on OneUI ported ROM, due to using oreo trustlets and mobicore in conjunction with pie keymaster and fingerprint.
I have tried to revert to oreo fingerprint, keymaster but that did not worked.

OneUI discussion link https://github.com/ananjaser1211/FloydQ_Reports/issues/158

**Comment by ivanmeler** [comment]
this has been fixed for some time now (few days short of a year) by
https://github.com/8890q/android_device_samsung_hero2lte/commit/5254adfd16083a5ca4a4b4d7154b27bf26a7ad5f

https://github.com/8890q/android_device_samsung_hero2lte/commit/bcc9fffb76fca7b9ee92dca9d6d79ba8d2d2d998

https://github.com/8890q/android_device_samsung_hero2lte/commit/dc5618465d48b01e88fa7d429b777ad3b0c03762

https://github.com/8890q/android_device_samsung_hero2lte/commit/57cc827695d225079a596b0264ea8683d055ade9

https://github.com/8890q/android_device_samsung_hero2lte/commit/b4a42f949492cd1b646ae2ebcc61ec588d5f4c3c

https://github.com/8890q/android_device_samsung_hero2lte/commit/68bf1defb1c449cb2be99e70656f30c40c32087f
