### ISSUE TITLE
In call echo

### ISSUE THREAD

**Issue by fcuzzocrea** [8890q/android_device_samsung_universal8890-common#2]
During a call, the called people ears an echo of its own voice. This is due to the noise cancelling mic acting.
So far I have tried to disable 2nd mic from mixer_paths but this did not worked.
The right solution would be to make lifevibes noise cancelling libraries working but currently those crashes : 

`09-10 10:54:09.197  3461 30995 E LvveTxBundle: LVVEFS_Android_Wrapper: Session 497: Session_SetConfig: ERROR format is wrong 5 5 1
09-10 10:54:09.198  3461 30995 E LvveTxBundle: LVVEFS_Android_Wrapper: Session 497: ProcessingFx_Command: cmdCode Case: ERROR EFFECT_CMD_CONFIGURE returned -22 from Session_SetConfig`

funny enough, the exact same crash is present even when using stock audio hal on aosp.

I have forward ported a patch for debugging lifevibes, but that currently does not work as well : https://review.lineageos.org/c/LineageOS/android_frameworks_av/+/286482

**Comment by fcuzzocrea** [comment]
A possible proposed fix, which fixed the issue for someone is : https://github.com/8890q/android_device_samsung_universal8890-common/commit/02a839a9f2b32851717d5aaa5310c10ebf35dc11

**Comment by ananjaser1211** [comment]
the current workaround i use in trelte (note4) is reducing the mic gain and earpiece gain to resolve echo during earpiece calls

and force speaker-mic to use 2nd mic

https://github.com/universal5433/android_device_samsung_treltexx/commit/b277e66545a9cbca74adae1849e926f1cfa9af50

also would help to cut off 2nd mic activity fully whenever `<ctl name="RCV Switch" value="1" />` . by adding `<ctl name="Sub Mic Switch" value="0" />`

the treltexx mixer cant be referenced fully as it was manually converted from MM tiny_ucm config into mixer_paths layout. which was imperfect. so i would not count on it very much. but it might help hero

of course all these are HACKS sadly

I am very curious if its even possible to bring up LiveVibes into AOSP as that would resolve this issue properly.

i just saw this org and i have to say, love the work you are putting in here.

**Comment by fcuzzocrea** [comment]
Thanks a lot for your reply !!

I'll try do tweak a bit more mixer paths to check if issue could be mitigated a bit. 
For life vibes, yeah it is definitely possible to have it working on aosp,  but one should be skilled enough in reversing all the stuff. I thought that importing blobbed stock audio hal would have fixed the issue but sadly there is still another piece missing.
Funny enough life vibes fails to load even when using libraries from flounder (nexus 9) which was basically using the audio hal from which the one we're using originated. 
Anyway Basyl Gello and Sean Hoyt had it working on cm14.1 on 5420 so it is definitely possible to have it working. 
It needs.. skills that I still miss. 
Same thing for the fp issue we have with the mix of fp blobs and mobicore

**Comment by tImIbreakdown** [comment]
@fcuzzocrea hi, is there any progress in this direction, did anything help? on leeco le 2 we have the same problem with the echo of the interlocutor, no one can help.
I also have no audio knowledge

**Comment by fcuzzocrea** [comment]
uhm sadly nope. if you are on los slack  feel free to ping me there !

**Comment by ivanmeler** [comment]
todo: probably could be somewhat mitigated by editing mixer gains, as a reference look at old lineage ones which are ugh complete mess

**Comment by ivanmeler** [comment]
mostly resolved now by https://github.com/8890q/android_device_samsung_universal8890-common/commit/f965582b2639d9a5a7a7b4e4c34fdf8f6ff524a8

and few other tweaks to mixers
