### ISSUE TITLE
Switch to samsung_slsi sepolicy

### ISSUE THREAD

**Issue by fcuzzocrea** [8890q/android_device_samsung_universal8890-common#3]
The current sepolicy is made on top of old 15.1 sepolicy plus rules added to adapt it to P and Q.
Since we did a complete rebase of both kernel and blobs, many rules can be dropped. 
It could be a good idea to switch to use common Samsung SLSI sepolicy and add missing rules on top.

**Comment by ivanmeler** [comment]
https://github.com/8890q/android_device_samsung_universal8890-common/commit/c5ab5af49c30baf357add8c34323a05e7c1a32f0

and later commits take care of this
