### ISSUE TITLE
graphics.composer fatal crash

### ISSUE THREAD

**Issue by aba-hollerer** [8890q/android_device_samsung_universal8890-common#4]
Hello Devs
First off I want to thank you for mainting this device code! I'm successfully running Lineageos-18.1 on the s7 flat.
However I needed the following fix to be able to build it (I know this does not concern you I just added this for completion):

```
project hardware/samsung/
diff --git a/hidl/thermal/android.hardware.thermal@2.0-service.samsung.rc b/hidl/thermal/android.hardware.thermal@2.0-service.samsung.rc
index ddc9104..17c14a5 100644
--- a/hidl/thermal/android.hardware.thermal@2.0-service.samsung.rc
+++ b/hidl/thermal/android.hardware.thermal@2.0-service.samsung.rc
@@ -1,4 +1,5 @@
 service vendor.thermal-hal-2-0 /vendor/bin/hw/android.hardware.thermal@2.0-service.samsung
+    interface android.hardware.thermal@1.0::IThermal default
     interface android.hardware.thermal@2.0::IThermal default
     class hal
     user system
```

I had 2 major bugs from which I was able to solve one namely the camera.
(*) After inspecting the working build of @ivanmeler of lineageos-18.0 at [xda-developers](https://forum.xda-developers.com/t/rom-lineageos-18-1-for-s7-exynos.4172749/) I figured that only the following libraries where different:

```
diff --git a/universal8890-common/proprietary/vendor/lib/hw/vendor.samsung.hardware.camera.provider@2.4-impl.so b/universal8890-common/proprietary/vendor/lib/hw/vendor.samsung.hardware.camera.provider@2.4-impl.so
index 12ccd5f3..e8d83d21 100644
Binary files a/universal8890-common/proprietary/vendor/lib/hw/vendor.samsung.hardware.camera.provider@2.4-impl.so and b/universal8890-common/proprietary/vendor/lib/hw/vendor.samsung.hardware.camera.provider@2.4-impl.so differ
diff --git a/universal8890-common/proprietary/vendor/lib64/hw/vendor.samsung.hardware.camera.provider@2.4-impl.so b/universal8890-common/proprietary/vendor/lib64/hw/vendor.samsung.hardware.camera.provider@2.4-impl.so
index 57893980..0831a40f 100644
Binary files a/universal8890-common/proprietary/vendor/lib64/hw/vendor.samsung.hardware.camera.provider@2.4-impl.so and b/universal8890-common/proprietary/vendor/lib64/hw/vendor.samsung.hardware.camera.provider@2.4-impl.so differ
```

So I copied them over and now the camera seems to work.
The other issue I'm unable to resolve is the graphics.composer. I get the following fatal in logcat whenever the screen tries to rotate (regardless of the app/Launcher wanting to rotate it):
[graphics.composer.log](https://github.com/8890q/android_device_samsung_universal8890-common/files/5736904/graphics.composer.log)

Is this a known issue?
I tried to copy over the stuff from the working build (*) again which did not work.
I also tried to revert from hwbinder to passthrough (change by @fcuzzocrea:Ic10e93398363f03551afe39715cb664bbbce1683)  but without success. The fatal crash is still persistent.

For now I just switched off the autorotate function but it would be nice if this would work (again?).

Can I be of any help to resolve this?

**Comment by aba-hollerer** [comment]
"Disabling HW overlays" in Developer Settings seems to be the workaround for now.

**Comment by fcuzzocrea** [comment]
Sorry for the late reply, but yes, disabling HW overlays from developer settings is the current only workaround. 

For stable trees, check LineageOS organization. We have the 18.1 bring up on lineageos gerrit

**Comment by aba-hollerer** [comment]
@fcuzzocrea 
I don't know if it still matters but I was able to fully resolve all my issues by using the proprietary blobs of the latest s7 flat build from https://www.los-legacy.de/ and the repositories @lineageos.

 -m     universal8890-common/proprietary/vendor/etc/init/wifi_sec.rc
 -m     universal8890-common/proprietary/vendor/lib/hw/hwcomposer.exynos5.so
 -m     universal8890-common/proprietary/vendor/lib/hw/memtrack.universal8890.so
 -m     universal8890-common/proprietary/vendor/lib/libExynosHWCService.so
 -m     universal8890-common/proprietary/vendor/lib/libexynosdisplay.so
 -m     universal8890-common/proprietary/vendor/lib/libexynosutils.so
 -m     universal8890-common/proprietary/vendor/lib/libexynosv4l2.so
 -m     universal8890-common/proprietary/vendor/lib/libhdmi.so
 -m     universal8890-common/proprietary/vendor/lib/libhwcutils.so
 -m     universal8890-common/proprietary/vendor/lib/libmpp.so
 -m     universal8890-common/proprietary/vendor/lib/libvirtualdisplay.so
 -m     universal8890-common/proprietary/vendor/lib64/hw/hwcomposer.exynos5.so
 -m     universal8890-common/proprietary/vendor/lib64/hw/memtrack.universal8890.so
 -m     universal8890-common/proprietary/vendor/lib64/libExynosHWCService.so
 -m     universal8890-common/proprietary/vendor/lib64/libexynosdisplay.so
 -m     universal8890-common/proprietary/vendor/lib64/libexynosutils.so
 -m     universal8890-common/proprietary/vendor/lib64/libexynosv4l2.so
 -m     universal8890-common/proprietary/vendor/lib64/libhdmi.so
 -m     universal8890-common/proprietary/vendor/lib64/libhwc2on1adapter.so
 -m     universal8890-common/proprietary/vendor/lib64/libhwc2onfbadapter.so
 -m     universal8890-common/proprietary/vendor/lib64/libhwcutils.so
 -m     universal8890-common/proprietary/vendor/lib64/libmpp.so
 -m     universal8890-common/proprietary/vendor/lib64/libvirtualdisplay.so
